name: On Release Push

on:
  push:
    branches:
      - release

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

  unit-tests:
    needs: build
    uses: ./.github/workflows/reusable-unit-tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/reusable-integration-tests.yml
    secrets: inherit